# Generated by Django 5.2.9 on 2026-03-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_theater_pricing_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ManyToManyField(to='movies.seat'),
        ),
    ]
