# Generated by Django 5.2.9 on 2026-03-25 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_booking_totalamount_remove_booking_seat_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='totalAmount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.seat'),
        ),
    ]
