# Generated by Django 5.2.9 on 2026-05-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_booking_seat_booking_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seat',
            new_name='seats',
        ),
    ]
